### ISSUE TITLE
Revenir sur un mode d'ajout de la couleur de la bouée quand elle est absolument prédictible

### ISSUE THREAD

**Issue by gdepuille** [ARIG-Robotique/robots#116]

**Comment by gdepuille** [comment]
@mistic100 Ton implémentation fonctionne plutôt bien sur les bouée unitaire, mais lors du démarrage avec Nerell on en prend deux en quasi simultané, et j'ai l'impression que la sélection de la couleur n'est pas génial.

Je contrôlerai mieux sur un prochain tests.

Je ré-ouvre pour trace.

**Comment by gdepuille** [comment]
Lors de la prise de deux bouée en simultané (départ de Nerell dans le grand port) il y a un bug de sélection de la couleur :

1. la couleur la plus proche est conservé pour les deux bouée ?
2. une des deux est en inconnu, et la lecture de la couleur merde ?

Il faut plus de log sur cette partie pour contrôler mieux.

**Comment by mistic100** [comment]
remplacé par une propriété "expected" comme en 2020, à tester
