### ISSUE TITLE
Odin prise grand port

### ISSUE THREAD

**Issue by mistic100** [ARIG-Robotique/robots#129]
- [x] brancher les maj du status
- [x] ne pas faire la seconde partie si les bouées ont été prises entre temps
- [ ] ne pas se centrer sur les chenaux si une seul bouée à déposer (pas fait, beaucoup de conditions, pas forcement utile)
- [x] ne pas faire la dépose si rien prit !
- [x] gestion coté jaune
- [ ] gestion entry point (pas fait, pas utile si ça reste une action monolithique)

**Comment by gdepuille** [comment]
Fix #88 si aucune autre action spécialisé est créer pour les déposes contre la bordure
