### ISSUE TITLE
Installation de Fedora sur VirtualBox

### ISSUE THREAD

**Issue by mistic100** [ARIG-Robotique/robots#21]
Ça peut servir, et parce que c'est pas la joie sans Ansible.

0. Installation auto !

-------

1. Config sudoers

```bash
su root
usermod dsorel -a -G wheel
```
- restart

-------

2. Addons invités
```bash
sudo dnf install dkms binutils gcc make patch libgomp glibc-headers glibc-devel kernel-headers kernel-devel
```
- insérer le disque
- installer
- si erreur, `sudo dnf install kernel-devel-$(uname -r)` puis recommencer
- restart

-------

3. Update system
```bash
sudo dnf update
```

-------

4. IntelliJ

https://www.jetbrains.com/idea/#chooseYourEdition

```bash
sudo mv ideaIC-2016-2.5.tar.gz /opt
sudo tar -xvf ideaIC-2016-2.5.tar.gz
sudo ln -sf /opt/ideaIC-2016-2.5.tar.gz /opt/idea
sudo ln -s /opt/idea/bin/idea.sh /usr/local/bin/idea
```

-------

5. GitKraken

https://www.gitkraken.com/download

```bash
sudo dnf install libXScrnSaver
sudo mv gitkraken-amd64.tar.gz /opt
sudo tar -xvf gitkraken-amd64.tar.gz
sudo ln -s /opt/gitkraken/gitkraken /usr/local/bin/gitkraken
```

-------

6. SSH

- copier dans ~/.ssh/id_rsa

```bash
chmod 600 ~/.ssh/id_rsa
```

-------

7. Divers

```bash
sudo dnf install git vim java-1.8.0-openjdk java-1.8.0-openjdk-devel nodejs npm
```

- config NPM https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory

-------

8. Plugins IntelliJ

- SVGViewer 2
- .ignore
- Markdown support

-------

9. Modules Node

```bash
npm install -g bower grunt-cli gulp-cli
```

-------

10. Chrome

```bash
sudo vim  /etc/yum.repos.d/google.repo
```
```txt
[google-chrome]
name=google-chrome - 64-bit
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
```
```bash
sudo dnf install google-chrome
```

-------

11. Git Workspace

```bash
wget https://raw.githubusercontent.com/StreakyCobra/gws/master/src/gws -O gws
chmod +x gws
sudo mv gws /usr/bin
```

------

12. mu-repo

```bash
sudo pip install mu-repo
```

------

13. Init Workspace

```bash
git clone git@github.com:ARIG-Robotique/arig-wksp.git
cd arig-wksp
./updateWorkspace.sh
```

**Comment by gdepuille** [comment]
This issue was moved to ARIG-Robotique/eurobot#61
