### ISSUE TITLE
Implémentation Lazy Theta* (any angle) pour le path

### ISSUE THREAD

**Issue by gdepuille** [ARIG-Robotique/robots#40]

**Comment by mistic100** [comment]
https://github.com/Ohohcakester/Any-Angle-Pathfinding

On trouve sur ce repo une implémentation du Lazy Theta* mais surtout le Anya16 qui est annoncé comme encore meilleur (à tester).

**Comment by mistic100** [comment]
Tests sur la map de base

## A*
> Runtime: 5.426953
> Path Length: 37.38477631085024

![astar](https://user-images.githubusercontent.com/41597/31629802-08690aba-b2b5-11e7-9a57-7f742511a3f4.gif)

## Lazy Theta*
> Runtime: 4.028101
> Path Length: 35.186869545796654

![lazy theta star](https://user-images.githubusercontent.com/41597/31629823-1302305a-b2b5-11e7-8513-c52eebb24858.gif)

## Anya16
> Runtime: 10.575762
> Path Length: 35.104521202314075

![anya16](https://user-images.githubusercontent.com/41597/31629851-2170bf1c-b2b5-11e7-808b-76a3166b1029.gif)

----------

Le Anya16 arrive à tracer en ligne droite, alors que le Lazy Theta* a au moins un point de passage en plein milieu.
