### ISSUE TITLE
Optimisation suivi du path

### ISSUE THREAD

**Issue by gdepuille** [ARIG-Robotique/robots#50]
Le premier mouvement lors du démarrage d'un nouveau path est un mouvement combiné Translation/Rotation. Cela a souvent pour effet de faire dévier le robot du premier segment de trajectoire.
Pour éviter ça il faudrait forcer le premier segment en ligne droite, dans un premier temps.

**Comment by mistic100** [comment]
est-ce que ça ne sera pas résolu si on fait les trajectoires en mode "aligne toi et avance"

**Comment by mistic100** [comment]
ok je l'avais pas compris comme ça, du coup on dit la même chose :-)

**Comment by gdepuille** [comment]
@mistic100 : De manière empirique, c'est surtout le premier mouvement qui est gênant et nous dévie de la trajectoire calculée.
Le mode "aligne toi et avance" implique de s’arrêter sur les points de passage. L'idée de cette petite évolution est de ne faire ça qu'au début et de continuer d’enchaîner les points de passage en combiner pour gagner du temps. Cela couplé avec ton travail sur le path qui génère des trajectoires moins "cassé" devrais limiter les grands angles à enchaîner qui entraîne de la dérive.

Du coup les deux cumulés et une vitesse d'orientation proportionnel à la vitesse de translation (avec une limite minimal) devrais nous donner de bonnes performances (en tous cas meilleurs qu'en 2017).

Dans le simulateur ça fait bien le boulot, maintenant il faudra voir en vrai avec les glissements centrifuge et centripète.
