### ISSUE TITLE
Prise de bouée "proche"

### ISSUE THREAD

**Issue by mistic100** [ARIG-Robotique/robots#82]
si on est très proche d'une bouée, ne pas faire le premier path pour aller au point d'approche, directement faire l'orientation et avance (distance à calculer)

**Comment by gdepuille** [comment]
Je vais ajouter un multiplicateur en complément de la base de 4 point correspondant au nombre de bouée présente dans les ventouses. Cela devrait avoir l'effet de remplir a fond avant de faire une dépose au fur et a mesure que l'on rempli et de ce qu'il reste de disponible

**Comment by gdepuille** [comment]
Après plusieurs tests le coefficient multiplicateur n'apporte rien.

Avec deux robots, il est fort probable que ce cas ne se présente pas vraiment.

A rediscuter @mistic100
